# Communicable, Maternal, Neonatal, and Nutritional Disease Burden (CMNN)

```{r}
# Load necessary packages
if(require(pacman)) install.packages(pacman)
pacman::p_load(tidyverse, knitr, here, janitor)

# Import the communicable diseases data
data_cmnn <- read_csv(here("data", "burden-of-disease-cmnn.csv"))
```

## Table of Estimates for CMNN Burden Over Time

```{r}
# Here render a table for the DALY burden over time for the three countries 
data_group7 <- data_cmnn %>% filter(Entity %in% c("Benin", "Nigeria", "Cameroon")) %>% clean_names() %>% 
  rename(DALYS = "dal_ys_disability_adjusted_life_years_communicable_maternal_neonatal_and_nutritional_diseases_sex_both_age_age_standardized_rate")

# You should pivot the data to show each country in a separate column.
pivot_group7_wide <- data_group7 %>%  pivot_wider(names_from = entity, 
                             values_from = DALYS, year) 
# Use kable() from the knitr package to render the table.
 kable(pivot_group7_wide)
```

## Plot Showing Trends in CMNN Burden Over Time

```{r}
# Here, plot a line graph showing the trend of DALY burden for the chosen countries over time. You can use ggplot2 to create this plot. Each country's line should be a different color.

pivot_group7_long <-  pivot_group7_wide %>% pivot_longer(names_to = "country",
                                       values_to = "value", -year)

pivot_group7_long %>% ggplot(aes( y= value, x= year, color= country))+
  geom_line()+
  labs(y= "DALYS")+
  labs(title = "Trends in DALYS by Country")
  


```

## Summary of CMNN Burden Findings

A comparison of DALY disease burden between Cameroon ,Nigeria and Benin shows a general downward trend. However, Cameroon had a higher DALY burden in the year 2000.


